# See https://docs.codecov.io/docs/codecov-yaml and other doc sections.

coverage:
  precision: 2
  round: down
  range: 60...100

  status:
    project:
      default:
        target: 75%

    patch:
      default:
        target: 75%
